ckeditor/ckeditor5-editor-classic

src/classiccreator.js

Part of ckeditor/ckeditor5#179.

Removed the temporal mock.

---

src/classiccreator.js
src/utils/imitatefeatures.js

Changed absolute import paths to relative.

---

src/utils/imitatefeatures.js
tests/manual/classiccreator.js
tests/manual/classiccreator.md

Related to https://github.com/ckeditor/ckeditor5-ui-default/issues/12.

t/ckeditor5-ui-default/12: Implement dropdown component

---

src/classiceditorui.js

Dependent on: https://github.com/ckeditor/ckeditor5-utils/pull/36

Changed config getter.

---

src/classic.js
src/classiceditorui.js
tests/classiceditorui.js

Part of https://github.com/ckeditor/ckeditor5-ui/issues/26.

T/ckeditor5 ui/26: Review our approach to MVVM

---

tests/manual/classic.js

Fixes: https://github.com/ckeditor/ckeditor5-typing/issues/17
Depends on: https://github.com/ckeditor/ckeditor5-typing/pull/24

Fixed tests after package merged.

---

tests/classic.js

Fixes required by ckeditor5-engine/t/518.

---

src/classic.js
src/classiceditorui.js
tests/classic.js
tests/classiceditorui.js

Changed paths and docs to use ckeditor5-core package

---

.jshintrc
tests/.jshintrc
tests/classic.js
tests/classiceditorui.js
tests/manual/classic.js

Fixed: Turn JSHint browser setting to false.

---

tests/manual/classic.html

Fixed path to ckeditor.css

---

src/classiceditorui.js
tests/classiceditorui.js
tests/manual/classic.js

FocusTracker integration

---

src/classic.js
src/classiceditorui.js
src/classiceditoruiview.js
tests/classic.js
tests/classiceditorui.js
tests/classiceditoruiview.js

t/38: Changes to EditorClassic after bringing *EditorUI back to life.

---

src/classic.js
tests/classic.js

Fixes #40. Requires https://github.com/ckeditor/ckeditor5-core/pull/48.

Implemented editor events

---

src/classiceditorui.js
tests/classiceditorui.js

Bind editable focus to view's document

---

src/classiceditoruiview.js
tests/classiceditoruiview.js
theme/theme.scss

Internal: Aligned the codebase after refactoring of the ck-editor-toolbar mixin in theme-lark. Closes #57.
---
Requires https://github.com/ckeditor/ckeditor5-theme-lark/pull/88.

t/57: Aligned the codebase after refactoring of the ck-editor-toolbar mixin in theme-lark

---

src/classiceditorui.js
tests/classiceditorui.js
tests/classiceditoruiview.js
tests/manual/tickets/60/1.html
tests/manual/tickets/60/1.js
tests/manual/tickets/60/1.md

Other: The toolbar should support a vertical offset from the top of the web page. Closes #60.
---
Requires https://github.com/ckeditor/ckeditor5-ui/pull/279.

t/60: The toolbar should support a vertical offset from the top of the web page

---

tests/manual/classiceditor.js
tests/manual/tickets/60/1.js

Tests: Minor adjustments in toolbar configurations (see ckeditor/ckeditor5#645).
---
* A piece of https://github.com/ckeditor/ckeditor5/issues/645.

t/ckeditor5/645: Minor adjustments in toolbar configurations

---

tests/manual/classiceditor.js
tests/manual/tickets/60/1.js

Other: Align code to the changes in naming UI components & commands.
---
* Minor PR - Check: https://github.com/ckeditor/ckeditor5-alignment/pull/25.

Other: Align code to the changes in naming UI components & commands.

---

src/classiceditorui.js

Internal: Simplify view property in `EditorUI`. Closes #81.
---
*For example – encountered issues, assumptions you had to make, other affected tickets, etc.*

Simplify view property in `EditorUI`

---

src/classiceditor.js
tests/classiceditorui.js

Internal: Aligned code to introduced error context. Required by ckeditor/ckeditor5-watchdog#2.
---
*For example – encountered issues, assumptions you had to make, other affected tickets, etc.*

Align code to introduced error context

---

tests/manual/classiceditor.js

Tests: Correct import statement.
---
* Related: ckeditor/ckeditor5-utils#294

Correct import statement

---

tests/classiceditor.js

Internal: Removed usage of the CKEditor 5 logger. Part of ckeditor/ckeditor5#383.
---
*For example – encountered issues, assumptions you had to make, other affected tickets, etc.*

Removed usage of logger.
